number1 = input ("Pick a number between 1 and 100")
number2 = input ("Pick a number between 1 and 100")
number3 = input ("Pick a number between 1 and 100")
number4 = input ("Pick a number between 1 and 100")
number5 = input ("Pick a number between 1 and 100")
number6 = input ("Pick a number between 1 and 100")
number7 = input ("Pick a number between 1 and 100")
number8 = input ("Pick a number between 1 and 100")
number9 = input ("Pick a number between 1 and 100")
number10 = input ("Pick a number between 1 and 100")

listsequence = [number1,number2,number3,number4,number5,number6,number7,number8,number9,number10]
print (listsequence)
high = max(listsequence)
print (high)
small = min(listsequence)
print (small)
